config/routes.rb
DaysIn2::Application.routes.draw do
    resources :comments, only: [:create, :destroy]
    resources :users
    resources :locations
    resources :ratings, only: :update
    resources :sessions, only: [:create, :new, :destroy]
    resources :scores, only: [:create, :destroy]
    resources :reviews, only: [:create, :search, :destroy, :update]
    root 'stat_pages#home'
    match '/reviewsearch', to: 'reviews#index', via: 'get'
    match '/signout',  to: 'sessions#destroy',    via: 'delete'
    match '/signin',   to: 'sessions#new',     via: 'get'
    match '/signup',  to: 'users#new',          via: 'get'
    match '/help',    to: 'stat_pages#help',    via: 'get'
    match '/contact', to: 'stat_pages#contact', via: 'get'
    match '/reviewshow',  to: 'reviews#review', via: 'get'
    match '/reviewfilter', to:'reviews#index', via: 'get'
    match '/reviewedit', to:'reviews#edit', via: 'get'

  

end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Write new comment..." %>
    <%= f.hidden_field :review_id, :value => @reviewpassed.id %>
  <% if signed_in? %><%= f.hidden_field :user_id, :value => current_user.id %> <% end %>
  </div>
  <%= f.submit "Post", class: "btn" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_review_filter.html.erb
<%= form_tag reviewfilter_path, :method => 'get' do %>
  <div class="field">
  	<%= label_tag :content, 'Keywords: ' %>
    <%= text_field_tag :content, params[:content], placeholder:"Guides that contain..." %>
  </div>
  <div class="field">
  	<%= label_tag :budgetck, 'Budget: ' %>
    <%= check_box_tag "budgetck[]", 1 %><%=' $'%><br>
    <%= check_box_tag "budgetck[]", 2 %><%=' $$' %><br>    
    <%= check_box_tag "budgetck[]", 4 %><%=' $$$'%>
  </div>
  <br>
  <div class="field">
  	<%= label_tag :category, 'Categories: ' %>
    <% cats = Review::CATEGORIES%> 
    <% cats.each do |c| %> <%= check_box_tag "[category][]", c%> <%= c %><br>
 	<% end %>
    </div><br>
  <div class="field">
  	<%= label_tag :timestamp, 'Only show results from: ' %>
    <%= select_tag :timestamp, "<option></option><option>Past week</option><option>Past month</option><option>Past year</option><option>Anytime</option>".html_safe %>
  </div>
  <div class="field">
    <%= label_tag :sort_order, 'Sort results by: ' %>
    <%= select_tag :sort_order, "<option>Upload date (newest first)</option><option>Upload date (oldest first)</option><option>Rating (highest first)</option><option>Rating (lowest first)</option><option>Viewed (most first)</option>".html_safe %> <br><br>
  </div>
    
    <%= submit_tag "Search", :name => nil, class: "btn" %>
    <%= hidden_field_tag :days, params[:days]%>
    <%= hidden_field_tag :city, params[:city]%>
    <%= hidden_field_tag :season, params[:season]%>
<% end %>	
<br>
<%= form_tag reviewfilter_path, :method => 'get' do %>
    <%= submit_tag "Reset", :name => nil, class: "btn" %>
    <%= hidden_field_tag :content, ''%>
    <%= hidden_field_tag :days, ''%>
    <%= hidden_field_tag :city, ''%>
    <%= hidden_field_tag :season, ''%>
    <%= hidden_field_tag :budget, ''%>
<% end %>	

app/views/shared/_review_form.html.erb
<%= form_for @review, html: {multipart: true} do |f| %>
          <%= f.hidden_field :lat %>
          <%# if @review.viewcount.nil? %>
          <%#= f.hidden_field :viewcount, :value => 0 %>
          <%# else %>
          <%#= f.hidden_field :viewcount, params[:viewcount] %>
          <%# end %>
          <%= f.hidden_field :lng %>
          <%= f.hidden_field :address%>
          <%= f.hidden_field :city%>
                    <%= f.hidden_field :location_name%>
          <%= f.hidden_field :district%>
                    <%= f.hidden_field :postcode%>
          <%= f.hidden_field :country%>
                    <%= f.hidden_field :phone_number%>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :days, "Number of Days" %>
    <%= f.text_field :days, placeholder: "" %>
  </div>
  <div class="field">
    <%= f.label :location_search, "City" %>
    <%= f.text_field :location_search, class:"form-text"%>     
    <%= render "stat_pages/googlemap" %>
    </div>
  <div class="field">
  <%= f.label :summary, "Summary (max 200 characters)" %>
    <%= f.text_area :summary, placeholder: "", class:"form-text" %>
      </div>      
  <div class="field">
    <%= f.label :content, "Review (don't hold back!)" %>
	    <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
      </div>
      <br>
  <div class="field">
      <%= f.label :image, "Cover photo" %>
    <%= f.file_field :image%>
      </div>      
  <div class="field">
        <%= f.label :season, "Season" %>
    <%= f.select :season, options_for_select([['Summer'], ['Winter'], ['Autumn'], ['Spring']])%>
      </div>
  <div class="field">
        <%= f.label :budget, "Budget" %>
    <%= f.select :budget, options_for_select([['$', 1], ['$$', 2], ['$$$', 3]]) %>
  </div>
  <div class="field">
       <%= f.label :category, "Category (select all that apply)" %>
  <ol class="thumbnails">
 	<% cats = Review::CATEGORIES%> 
    <% cats.each do |c| %> <li> <%= check_box_tag "review[category][]", c%> <%= c %> <br>
 	<% end %></li>
 	</div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<%= tinymce %>
<% end %>

app/views/shared/_score_review.html.erb
<%= form_for(@score) do |f| %>
    <div class="field">
    <%= f.select :score, options_for_select([[1], [2], [3], [4], [5]])%>
    <%= f.hidden_field :review_id, :value => @reviewpassed.id %>
    <%= f.hidden_field :reviewer_id, :value => current_user.id %>
      </div>
  <%= f.submit "Rate", class: "btn btn-large btn-primary" %>
  
<% end %>                               

app/views/shared/_user_info.html.erb
<h2 class="pull-left">   <%= image_tag(@user.dp_url(:thumb), height:'50', width:'50') if @user.dp?%></h2><br>
<h3 class="featurette-heading pull-left"><br>     <%= @user.name %></h3>
        <br>
        <h2 class="lead"><%= @user.location %></h2>
    