config/routes.rb
DaysIn2::Application.routes.draw do
    resources :comments, only: [:create, :destroy]
    resources :users
    resources :locations
    resources :ratings, only: :update
    resources :sessions, only: [:create, :new, :destroy]
    resources :scores, only: [:create, :destroy]
    resources :reviews, only: [:create, :search, :destroy, :update]
    root 'stat_pages#home'
    match '/reviewsearch', to: 'reviews#index', via: 'get'
    match '/signout',  to: 'sessions#destroy',    via: 'delete'
    match '/signin',   to: 'sessions#new',     via: 'get'
    match '/signup',  to: 'users#new',          via: 'get'
    match '/help',    to: 'stat_pages#help',    via: 'get'
    match '/contact', to: 'stat_pages#contact', via: 'get'
    match '/reviewshow',  to: 'reviews#review', via: 'get'
    match '/reviewfilter', to:'reviews#index', via: 'get'
    match '/reviewedit', to:'reviews#edit', via: 'get'

  

end

app/controllers/stat_pages_controller.rb
class StatPagesController < ApplicationController
  def home
      @review = Review.new
  end
  def contact
  end
  def help
  end
    def search
        end
end

app/helpers/stat_pages_helper.rb
module StatPagesHelper
end

app/views/stat_pages/_form.html.erb
<aside class="span4">
<br>
<h3 class="lead"> Where do YOU want to go? </h3>
<%= form_for(@review, url: reviewsearch_path, method: "get") do |f| %>
          <%= f.hidden_field :lat%>
          <%= f.hidden_field :lng%>          <div class="field">
                    <%= label_tag :city, "Location" %>
        <%= text_field_tag :location_search, nil, type: "search" %>
              <%= label_tag :days, "Number of Days" %>
         <%= text_field_tag(:days, params[:days], placeholder: "Days") %>

                <%= label_tag :season, "Season" %>        
                    <%= select_tag :season, "<option>Summer</option><option>Autumn</option><option>Winter</option><option>Spring</option>".html_safe, :prompt => "Any"%></div>
                                  <%= submit_tag "Search", :name => nil, class: "btn"%>          
<% end %><br>
</aside>
<center>                               <%= render partial: "googlemapsearch" %></center>

app/views/stat_pages/_googlemap.html.erb
<div id="googlemap"></div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">	
<!--
  var defaultZoom = 16; // Why zoomed in? Because it looks good.  
    
  // create map and add controls
  var mapOptions = {
    center: new google.maps.LatLng(13.731547730050778, 100.56798934936523),
    zoom: defaultZoom,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scrollwheel: false,
    scaleControl: false
  };
  var map = new google.maps.Map(document.getElementById('googlemap'),mapOptions);
	
	// I'm Centering the map in Melbourne
	// '37.8136S'
	// '144.9631E'
	var mylat = document.getElementById("review_lat").value;
	var mylng = document.getElementById("review_lng").value;
	if (jQuery.isEmptyObject(mylat)) {
	  var mylat = '-37.8136';
	  var mylng = '144.9631';
	  var defaultZoom = 14;
	};

	// set center point of map to be of the Marker or the Default City
  var centrePoint = new google.maps.LatLng(mylat, mylng);
  map.setCenter(centrePoint);
  map.setZoom(defaultZoom); 
	
	// add a draggable marker
  marker = new google.maps.Marker({
    map: map,
    draggable: true,
    animation: google.maps.Animation.DROP,
    position: centrePoint
  });

  var defaultImage = new google.maps.MarkerImage(
      "http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      new google.maps.Size(71, 71),
      new google.maps.Point(0, 0),
      new google.maps.Point(17, 34),
      new google.maps.Size(35, 35));
  marker.setIcon(defaultImage);
	
  google.maps.event.addListener(marker, 'click', toggleBounce);
	
	// create Info window for marker
  var infowindow = new google.maps.InfoWindow();
  
  // Address Autocomplete
  var input = document.getElementById('review_location_search');
  var autocomplete = new google.maps.places.Autocomplete(input);
  autocomplete.bindTo('bounds', map);
  
	// add a drag listener to the map
	google.maps.event.addListener(marker, "dragend", function() {
		var point = marker.getPosition();
		map.panTo(point);
		document.getElementById("review_lat").value = point.lat();
		document.getElementById("review_lng").value = point.lng();
		infowindow.close();
    marker.setIcon(defaultImage);
  });
  var place;
  var photos;

  // Autocomplete Listener
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    place = autocomplete.getPlace();
    marker.setPosition(place.geometry.location);
    map.panTo(place.geometry.location);
    map.setZoom(16);
		document.getElementById("review_lat").value = place.geometry.location.lat();
		document.getElementById("review_lng").value = place.geometry.location.lng();
		
		// Sets the proper image on the marker. ie. school/hospital marker
		var image = new google.maps.MarkerImage(
        place.icon,
        new google.maps.Size(71, 71),
        new google.maps.Point(0, 0),
        new google.maps.Point(17, 34),
        new google.maps.Size(35, 35));
    marker.setIcon(image);
    marker.setPosition(place.geometry.location);

    var address = '';
    if (place.address_components) {
      address = [(place.address_components[0] &&
                  place.address_components[0].short_name || ''),
                 (place.address_components[1] &&
                  place.address_components[1].short_name || ''),
                 (place.address_components[2] &&
                  place.address_components[2].short_name || '')
                ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
    
    // Autofill the fields in the form. TODO: improve parsing of the returned JSON data.
    var address = place.address_components;
    var website = place.url;

    if (address[address.length - 1]) {
      var zipcode = address[address.length - 1].long_name;
    };
    if (address[address.length - 2]) {
      var country = address[address.length - 2].long_name;
    };
    if (address[address.length - 3]) {
      var city = address[address.length - 3].long_name;
    };
    if (address[address.length - 4]) {
      var sublocality = address[address.length - 4].long_name;
    };
    if (address[0]) {
      var streetnumber = address[0].long_name;
    };
    if (address[1]) {
      var streetname = address[1].long_name;
    };
    if (place.name) {
      var location_name = place.name;
    }
    var formatted_address = place.formatted_address;
    var formatted_phone_number = place.formatted_phone_number;
    
    if (zipcode){
      document.getElementById("review_postcode").value = zipcode;
    }
    if (city) {
      document.getElementById("review_city").value = location_name;
    }
    if (country) {
      document.getElementById("review_country").value = country;
    }
    if (sublocality) {
      document.getElementById("review_district").value = sublocality;
    }
    if (streetname) {
      document.getElementById("review_address").value = streetname;
    }
    if (location_name) {
      document.getElementById("review_location_name").value = city;
    }
    if (formatted_phone_number) {
      document.getElementById("review_phone_number").value = formatted_phone_number;
    }
    photos = place.photos;
    $('#place_images').empty();
    for (var i = 0; i < photos.length; i++) {
      var url = photos[i].getUrl({maxHeight: "1280", maxWidth: "1280"});
      $('#place_images').prepend('<img src="' + url + '"/>');
    }
  });
  // This is the function to animate the marker after dropping it.
  function toggleBounce() {
  google.maps.event.trigger(map, 'resize')
    if (marker.getAnimation() != null) {
      marker.setAnimation(null);
    } else {
      marker.setAnimation(google.maps.Animation.BOUNCE);
    }
  };

//-->
</script>

<br />

app/views/stat_pages/_googlemapsearch.html.erb
<div id="googlemap"></div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">	
<!--
  var defaultZoom = 16; // Why zoomed in? Because it looks good.  
    
  // create map and add controls
  var mapOptions = {
    center: new google.maps.LatLng(13.731547730050778, 100.56798934936523),
    zoom: defaultZoom,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scrollwheel: false,
    scaleControl: false
  };
  var map = new google.maps.Map(document.getElementById('googlemap'),mapOptions);
	
	// I'm Centering the map in Melbourne
	// '37.8136S'
	// '144.9631E'
	var mylat = document.getElementById("review_lat").value;
	var mylng = document.getElementById("review_lng").value;
	if (jQuery.isEmptyObject(mylat)) {
	  var mylat = '-37.8136';
	  var mylng = '144.9631';
	  var defaultZoom = 7;
	};

	// set center point of map to be of the Marker or the Default City
  var centrePoint = new google.maps.LatLng(mylat, mylng);
  map.setCenter(centrePoint);
  map.setZoom(defaultZoom); 
	
	// add a draggable marker
  marker = new google.maps.Marker({
    map: map,
    draggable: true,
    animation: google.maps.Animation.DROP,
    position: centrePoint
  });

  var defaultImage = new google.maps.MarkerImage(
      "http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      new google.maps.Size(71, 71),
      new google.maps.Point(0, 0),
      new google.maps.Point(17, 34),
      new google.maps.Size(35, 35));
  marker.setIcon(defaultImage);
	
  google.maps.event.addListener(marker, 'click', toggleBounce);
	
	// create Info window for marker
  var infowindow = new google.maps.InfoWindow();
  
  // Address Autocomplete
  var input = document.getElementById('location_search');
  var autocomplete = new google.maps.places.Autocomplete(input);
  autocomplete.bindTo('bounds', map);
  
	// add a drag listener to the map
	google.maps.event.addListener(marker, "dragend", function() {
		var point = marker.getPosition();
		map.panTo(point);
		document.getElementById("review_lat").value = point.lat();
		document.getElementById("review_lng").value = point.lng();
		infowindow.close();
    marker.setIcon(defaultImage);
  });
  var place;
  var photos;

  // Autocomplete Listener
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    place = autocomplete.getPlace();
    marker.setPosition(place.geometry.location);
    map.panTo(place.geometry.location);
    map.setZoom(7);
		document.getElementById("review_lat").value = place.geometry.location.lat();
		document.getElementById("review_lng").value = place.geometry.location.lng();
		
		// Sets the proper image on the marker. ie. school/hospital marker
		var image = new google.maps.MarkerImage(
        place.icon,
        new google.maps.Size(71, 71),
        new google.maps.Point(0, 0),
        new google.maps.Point(17, 34),
        new google.maps.Size(35, 35));
    marker.setIcon(image);
    marker.setPosition(place.geometry.location);

    var address = '';
    if (place.address_components) {
      address = [(place.address_components[0] &&
                  place.address_components[0].short_name || ''),
                 (place.address_components[1] &&
                  place.address_components[1].short_name || ''),
                 (place.address_components[2] &&
                  place.address_components[2].short_name || '')
                ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
    
    // Autofill the fields in the form. TODO: improve parsing of the returned JSON data.
    var address = place.address_components;
    var website = place.url;

    if (address[address.length - 1]) {
      var zipcode = address[address.length - 1].long_name;
    };
    if (address[address.length - 2]) {
      var country = address[address.length - 2].long_name;
    };
    if (address[address.length - 3]) {
      var city = address[address.length - 3].long_name;
    };
    if (address[address.length - 4]) {
      var sublocality = address[address.length - 4].long_name;
    };
    if (address[0]) {
      var streetnumber = address[0].long_name;
    };
    if (address[1]) {
      var streetname = address[1].long_name;
    };
    if (place.name) {
      var location_name = place.name;
    }
    var formatted_address = place.formatted_address;
    var formatted_phone_number = place.formatted_phone_number;
    
    if (zipcode){
      document.getElementById("review_postcode").value = zipcode;
    }
    if (city) {
      document.getElementById("review_city").value = location_name;
    }
    if (country) {
      document.getElementById("review_country").value = country;
    }
    if (sublocality) {
      document.getElementById("review_district").value = sublocality;
    }
    if (streetname) {
      document.getElementById("review_address").value = streetname;
    }
    if (location_name) {
      document.getElementById("review_location_name").value = city;
    }
    if (formatted_phone_number) {
      document.getElementById("review_phone_number").value = formatted_phone_number;
    }
    photos = place.photos;
    $('#place_images').empty();
    for (var i = 0; i < photos.length; i++) {
      var url = photos[i].getUrl({maxHeight: "1280", maxWidth: "1280"});
      $('#place_images').prepend('<img src="' + url + '"/>');
    }
  });
  // This is the function to animate the marker after dropping it.
  function toggleBounce() {
  google.maps.event.trigger(map, 'resize')
    if (marker.getAnimation() != null) {
      marker.setAnimation(null);
    } else {
      marker.setAnimation(google.maps.Animation.BOUNCE);
    }
  };

//-->
</script>

<br />

app/views/stat_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Days In - Plan your next trip here!</h1>
<p>
Feedback? Complaints? Compliments? Contact us here.
</p>

app/views/stat_pages/help.html.erb
<% provide(:title, 'Help') %>
<br><br><h2 class="featurette-heading">Help</h2><br><br>

<div class="tabbable tabs-left">
 <ul class="nav nav-tabs" id="proftabs">
 <li><a href="#instruction_tab" data-toggle="tab" > How Nimbus Works </a></li>
 <li><a href="#about_tab" data-toggle="tab" > About Us </a></li>
  <li><a href="#contact_us_tab" data-toggle="tab">Contact Us</a></li>
  </ul>
  <div class="tab-content">
    <div id="instruction_tab" class="tab-pane">

    </div>
    <div id="about_tab" class="tab-pane">
    Make this look like a fun resume.
	<br> 
	Made by travel addicts for travel addicts! Whether you're a hithchiker, backpacker, newlywed couple, family or a business traveller, Days In has you covered when planning your next trip. 	<br> 
	   <br>
   </div>
          
   <div id="contact_us_tab" class="tab-pane">
      
		<br>
          
		  Test
		  
		  Test
      
		  </br>
   </div>
      
    
          </div>
          
        
		</div>

app/views/stat_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center hero-unit">
<h1 class="featurette-heading">The Nimbus Project</h1>
<h2 class="lead">Browse through thousands of the best travel blogs and guides here!</h3>
<br>
<section>
<%= render 'form' %>
</section>
<% if signed_in? %>

</div>
<% else %>
<br>
Want to earn money for your travel reviews? 
<br>If your guides are among our most popular, we'll pay you to keep writing!
<br><br>
<%= link_to "Sign up", signup_path, class: "btn btn-large" %> <%= link_to "Sign in", signin_path, class: "btn btn-large" %> 
<br> OR <br>
<%= link_to "Find out more!", help_path, class: "btn btn-large" %>
</div>
<%end %>