config/routes.rb
DaysIn2::Application.routes.draw do
    resources :comments, only: [:create, :destroy]
    resources :users
    resources :locations
    resources :ratings, only: :update
    resources :sessions, only: [:create, :new, :destroy]
    resources :scores, only: [:create, :destroy]
    resources :reviews, only: [:create, :search, :destroy, :update]
    root 'stat_pages#home'
    match '/reviewsearch', to: 'reviews#index', via: 'get'
    match '/signout',  to: 'sessions#destroy',    via: 'delete'
    match '/signin',   to: 'sessions#new',     via: 'get'
    match '/signup',  to: 'users#new',          via: 'get'
    match '/help',    to: 'stat_pages#help',    via: 'get'
    match '/contact', to: 'stat_pages#contact', via: 'get'
    match '/reviewshow',  to: 'reviews#review', via: 'get'
    match '/reviewfilter', to:'reviews#index', via: 'get'
    match '/reviewedit', to:'reviews#edit', via: 'get'

  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    before_action :signed_in_user, only: [:create, :search, :destroy]
    before_action :correct_user,   only: [:destroy, :update]
    def index
        if params[:budgetck] == nil
            params[:budget] = ''
        else
            params[:budget] = params[:budgetck].map{ |i| i.to_i }.inject{|sum, x| sum + x}
        end
        @users = User.paginate(page: params[:page])
        case params[:sort_order]
            when "Upload date (oldest first)"
            @sort_order = 'created_at ASC'
            when "Upload date (newest first)"
            @sort_order = 'created_at DESC'
            when "Rating (highest first)"
            @sort_order = 'average_rating DESC'
            when "Rating (lowest first)"
            @sort_order = 'average_rating ASC'
        end
        @reviewtest = Review.paginate(page: params[:page]).search(params[:days], params[:location_search], params[:season], params[:content]).search_budget(params[:budget]).search_timestamp(params[:timestamp])
        
        if params[:category]==nil
           @reviewcompile = @reviewtest.search_category(params[:category])
        else
            @reviewcompile = @reviewtest
            params[:category].each do |cats|
                @merger = @reviewtest.search_category(cats)
                @reviewcompile = @reviewcompile.merge(@merger)
            end
        end
        
       
        
        if @reviewcompile == []
            @reviews = 1
        else
            @reviews = @reviewcompile.all(:order => @sort_order)
            
        end
        end
    def destroy
        @review.destroy
        redirect_to current_user
    end

    def review
        @reviewpassed = Review.find_by(id: params[:id])
        @hash = Gmaps4rails.build_markers(@reviewpassed) do |user, marker|
            marker.lat user.lat
            marker.lng user.lng
        end
        impressionist(@reviewpassed)
        if signed_in? && @reviewpassed.user_id != current_user.id
        if Rating.exists?(review_id: @reviewpassed.id, user_id: @current_user.id)
        @rating = Rating.where(review_id: @reviewpassed.id, user_id: @current_user.id).first
        else
        @rating = Rating.create(review_id: @reviewpassed.id, user_id: @current_user.id, score: 0)
        end
        end
    end
    def edit
        @reviewedit = Review.find_by(id: params[:id])
    end
    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to current_user
            else
            redirect_to current_user
            end
    end
    def update
        @reviewedit = Review.find_by(id: params[:id])
        if @reviewedit.update_attributes(review_params)
            flash[:success] = "Review updated"
            redirect_to current_user
            else
            redirect_to current_user
        end
    end
    private
    def correct_user
        @review = current_user.reviews.find_by(id: params[:id])
        redirect_to current_user if @review.nil?
    end
    def review_params
        params.require(:review).permit(:content, :days, :viewcount, :city, :budget, :season, :location_search, :country, :district, :address, :location_name, :postcode, :phone_number, :lat, :lng, :summary, :image, :category => [])
    end
end

app/views/reviews/_review.html.erb
<li class="thumbnails">
<div class="well">
  <span class="title"><b><%= link_to "#{pluralize(review.days, "day")} in #{review.city} in #{review.season} (Budget: #{review.budget})", reviewshow_path(:id => review.id), 'data-no-turbolink' => true%></b></span>
      Summary: <%= review.summary %>
    <br>
    <i> Viewed: <%= pluralize(review.impressionist_count(:filter =>:ip_address), "time") %> </i>
	<div class="image_placeholder">    <%= image_tag review.image_url %></div>    <br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(review.created_at) %> ago.   
    <% if current_user?(review.user) %>
    <%= link_to "(Delete)", review, method: :delete,
                                     data: { confirm: "Are you sure?" },
                                     title: review.content %>
    <%= link_to "(Edit)", reviewedit_path(:id => review.id), 'data-no-turbolink' => true%>
    <% end %>
  </span>
    
  </span>
</div>
</li>

app/views/reviews/edit.html.erb
<%= form_for @reviewedit, html: {multipart: true} do |f| %>
          <%= f.hidden_field :lat %>
          <%= f.hidden_field :lng %>
          <%= f.hidden_field :address%>
          <%= f.hidden_field :city%>
                    <%= f.hidden_field :location_name%>
          <%= f.hidden_field :district%>
                    <%= f.hidden_field :postcode%>
          <%= f.hidden_field :country%>
                    <%= f.hidden_field :phone_number%>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :days, "Number of Days" %>
    <%= f.text_field :days, placeholder: "" %>
  </div>
  <div class="field">
    <%= f.label :location_search, "City" %>
    <%= f.text_field :location_search, class:"form-text"%>     
    <%= render "stat_pages/googlemap" %>
    </div>
  <div class="field">
  <%= f.label :summary, "Summary (max 200 characters)" %>
    <%= f.text_area :summary, placeholder: "", class:"form-text" %>
      </div>      
  <div class="field">
    <%= f.label :content, "Review (don't hold back!)" %>
    <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
      </div>
      <br>
  <div class="field">
      <%= f.label :image, "Cover photo" %>
    <%= f.file_field :image%>
      </div>      
  <div class="field">
        <%= f.label :season, "Season" %>
    <%= f.select :season, options_for_select([['Summer'], ['Winter'], ['Autumn'], ['Spring']])%>
      </div>
  <div class="field">
        <%= f.label :budget, "Budget" %>
    <%= f.select :budget, options_for_select([['$', 1], ['$$', 2], ['$$$', 3]]) %>
  </div>
  <div class="field">
       <%= f.label :category, "Category (select all that apply)" %>
  <ol class="thumbnails">
 	<% cats = Review::CATEGORIES%> 
    <% cats.each do |c| %> <li> <%= check_box_tag "review[category][]", c%> <%= c %> <br>
 	<% end %></li>
 	</div>
  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<%= tinymce %>
<% end %>

app/views/reviews/index.html.erb
<% provide(:title, 'Search results') %>
<br>
<h2 class="featurette-heading">Guides</h2>
<h4>Filter by:</h4>
<div class="row">
<br>
<aside class="span4">
<%= render 'shared/review_filter' %>
</aside>


<% if @reviews == 1 %>

<section class="span8">
Sorry, no results found. Been there already?<br><br> 
<%= link_to_if signed_in?, "Post your own!", current_user, class: "btn" do link_to("Post your own!", signin_path, class: "btn")
end %>
</section>

<% else %>

<section class="span8">
<%= will_paginate @reviews%>
<ol class="reviews">
      <% @reviews.each do |review| %>
      <li>
      <%= link_to "#{pluralize(review.days,"day")} in #{review.city} in #{review.season}", reviewshow_path(:id => review.id), 'data-no-turbolink' => true %> by <%= link_to User.find_by(id: review.user_id).name, User.find_by(id: review.user_id)%>.
      <span class="timestamp"> 
      <i>Posted <%= time_ago_in_words(review.created_at) %> ago.</i><br>
      <b>Summary: </b><%= review.summary %>
      </span><br>
      (Rating: <% if Rating.exists?(review_id: review.id)%> <%="#{'%.1f' % review.average_rating}" %>) <% else %> Unrated) <%end%>
      <% end %>
      </li>                                       
                                    
</ol>
</section>
<% end %>
</div>

app/views/reviews/review.html.erb
<% provide(:title, 'Guide') %>
<br>
<h1 class="featurette-heading"> <%= "#{@reviewpassed.days}"%> days in <%= "#{@reviewpassed.city}"%> in <%= "#{@reviewpassed.season}"%></h1>
<h2>    by <%= link_to User.find_by(id: @reviewpassed.user_id).name, User.find_by(id: @reviewpassed.user_id)%> <br></h2>
    <br>
  
  
    <!--  consult Bootstrap docs at
        http://twitter.github.com/bootstrap/javascript.html#carousel -->
  <div id="this-carousel-id" class="carousel slide">
    <div class="carousel-inner">
      <div class="active item">
	              <center>
	              <div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
	              <script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

</center>
      </img>
	    <div class="carousel-caption">
<h4 class="lead pull-right">Map</h4>
          </div>
        </div>        
      <% if @reviewpassed.image? %>
      <div class="item">
      <center><%= image_tag(@reviewpassed.image, :size => '600x400')%></center>
	      <div class="carousel-caption">
	      <h4 class="lead pull-right">Image</h4>
          </div>

        </div>
        <% end %>
      </div>

    </div>
      <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
    

<script>
$(function(){
$('#this-carousel-id').carousel();
});
</script>   
        

        <b>Created on:</b> <%= "#{@reviewpassed.created_at.to_formatted_s(:long_ordinal)}"%>
<br>
<b>Keywords:</b> <%= "#{@reviewpassed.category.join(', ')}"%>
            <br>
            <b>Budget:</b> <%= "#{@reviewpassed.budget}"%><br>
            <b>Viewed:</b> <%= "#{pluralize(@reviewpassed.impressionist_count(:filter=>:ip_address), "time")}" %>
<br>
<b>Averate rating:</b>
<% if Rating.exists?(review_id: @reviewpassed.id)%>
<div id="star"></div>
	<script>
  $('#star').raty({
    readOnly: true,
    score: <%= @reviewpassed.average_rating %>,
    path: '/assets',
    halfShow: true
  });
  </script>
<% else %>
Unrated.
<% end %>

            
<% if signed_in? && @reviewpassed.user_id != current_user.id%>

<b>Your rating:</b>
<div id="user_star">
<script>	
  $('#user_star').raty({
    score: <%= @rating.score %>,
    path: '/assets',
    click: function(score, evt) {
      $.ajax({
        url: '/ratings/' + <%= @rating.id %>,
        type: 'PATCH',
        data: { score: score }
      });
    }
  });
</script>
</div>

<% elsif signed_in? && @reviewpassed.user_id == current_user.id %>
<br>
<b><%= link_to("Edit this review?", reviewedit_path(id: @reviewpassed.id))%></b><br>

<% else %>
<%= link_to("Sign in to rate and comment on this travel guide", signin_path) %>
<% end %>

<hr class="featurette-divider">
<div class="featurette">
<section>
<%= @reviewpassed.content.html_safe%>
            <br>           
            
</section>
</div>
<hr class="featurette-divider">
<section>
<% if signed_in? %>
Comments go here
<% end %>
If any comments put them here
<h2 class="pull-left">Comments (Count comments)</h3>
<ol class="comments">
Render the comments
</ol>
Remember to paginate comments
End
</section>
</div>