config/routes.rb
DaysIn2::Application.routes.draw do
    resources :comments, only: [:create, :destroy]
    resources :users
    resources :locations
    resources :ratings, only: :update
    resources :sessions, only: [:create, :new, :destroy]
    resources :scores, only: [:create, :destroy]
    resources :reviews, only: [:create, :search, :destroy, :update]
    root 'stat_pages#home'
    match '/reviewsearch', to: 'reviews#index', via: 'get'
    match '/signout',  to: 'sessions#destroy',    via: 'delete'
    match '/signin',   to: 'sessions#new',     via: 'get'
    match '/signup',  to: 'users#new',          via: 'get'
    match '/help',    to: 'stat_pages#help',    via: 'get'
    match '/contact', to: 'stat_pages#contact', via: 'get'
    match '/reviewshow',  to: 'reviews#review', via: 'get'
    match '/reviewfilter', to:'reviews#index', via: 'get'
    match '/reviewedit', to:'reviews#edit', via: 'get'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ESK
  </small>
  <nav>
    <ul>
    Add S.N. tags here
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Nimbus", root_path, id: "logo", 'data-no-turbolink' => true %>
          <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Help", help_path, id:"menu_item" %></li>
          <li><%= link_to "Browse", reviewsearch_path, id:"menu_item" %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path, id:"menu_item" %></li>
          <% end %>
        </ul>
      </nav>
        </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nimbus: Travel guides for each city | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
                                            <%= stylesheet_link_tag 'gmaps4rails' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>  
  <script src="js/bootstrap.min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>

   <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
            <div class='flash'>
        <%= bootstap_flash %>
      </div>
      <%= yield %>


    </div>

  </body>
  <%= yield :scripts %>
            <%= render 'layouts/footer' %>
                  <%= debug(params) if Rails.env.development? %>
</html>